### ISSUE TITLE
Using composer ..

### ISSUE THREAD

**Issue by S1SYPHOS** [rosell-dk/webp-express#1]
.. would be great!

**Comment by rosell-dk** [comment]
not sure how to do that the best way.
The plugin itself is not going to be installed with composer, but through the Wordpress installer. The vendor libraries will have to be part of the plugin.

It would perhaps be nice development-wise to be able to update the vendor libraries with composer. On the other hand, I do not want to *have to* release new versions of the vendor libraries in order to use it here. Perhaps github submodule would be a better choice here.

Right now, I simply copy files over, when I change the dependent libraries. I could improve that process with a rsync script.

**Comment by marko-stimac** [comment]
You can use https://wpackagist.org to install Wordpress plugins, it works nice 👍

**Comment by rosell-dk** [comment]
The plugin *here on github* now uses composer. I still include the vendor files on the svn. It is probably best so.

For the few, who might be using this thing here on github: To get the dependent libraries, you need to cd into the plugin dir and run `composer update`. This gets you the latest dev releases of "webp-convert" and "webp-convert-cloud-service" on github. You must change the composer.json if you rather want the latest stable release (remove the repositories and change the minimum requirements). On the svn, I simply rsync everything, including the vendor folder, before committing.
