### ISSUE TITLE
 Fatal error: Uncaught ImagickException: NoDecodeDelegateForThisImageFormat 

### ISSUE THREAD

**Issue by tuami** [rosell-dk/webp-express#111]
http://prntscr.com/ltjibf

Hi see Screenshot, when i go to the plugin setting page i get this error. How can i solve this? Thank You

**Comment by rosell-dk** [comment]
Ok, that was surprising: There is Imagick on your system, but it seems Imagick is compiled without ability to handle jpeg files.

I can fix this, but I will not make a 0.8.2 release for it, because it probably only affects very few.
While waiting for 0.9.0, you can do this:

1. Open `/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/src/Converters/ConverterHelper.php` in a text-editor.
2. Remove the following lines:

```
        // Try Imagick extension
        if (extension_loaded('imagick') && class_exists('\\Imagick')) {
            $img = new \Imagick($filename);

            // The required function is available as from PECL imagick v2.2.2
            // (you can see your version like this: phpversion("imagick"))
            if (method_exists($img, 'getImageCompressionQuality')) {
                return $img->getImageCompressionQuality();
            }
        }
```

3. Open `/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/build/webp-on-demand-2.inc` in a text-editor.

4. Remove the same lines as above (line 294 - 305)

**Comment by rosell-dk** [comment]
Fixed in *WebP Convert* library: https://github.com/rosell-dk/webp-convert/issues/93
The fix will be part of next release

**Comment by rosell-dk** [comment]
Fixed in 0.9.0, which just has been released in the Wordpress directory

**Comment by rosell-dk** [comment]
Ah, I see the mistake. I should have written `catch (\ImagickException $e)` instead of `catch (ImagickException $e)`. Can you try to test that for me? Edit `wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/src/Converters/ConverterHelper.php`. It is line 272. Actually, as we want to ignore *any* exception, please test the following change.

Change line 272

from:
`} catch (ImagickException $e) {`

to:
`} catch (\Exception $e) {`

**Comment by rosell-dk** [comment]
The issue has been fixed (the code above has been released). Just forgot to close the issue
