### ISSUE TITLE
Missing content-length header when Serving existing converted image

### ISSUE THREAD

**Issue by cantoute** [rosell-dk/webp-express#130]
in the context (jpg in my test)
x-webp-convert-status: Serving existing converted image

seems like a little thing got forgotten... content-length

gr8 job man thanks for your efforts

and looks like I see an other strange thing

when activated "redirect" still returns the image (with content-length) with status 200 while this in header... did you want it to send a 301 redirect?

x-webp-express: Redirected directly to existing webp

**Comment by rosell-dk** [comment]
Regarding the header: Yes, you are right, the plugin should serve a Content-Length header. I have created [an issue](https://github.com/rosell-dk/webp-convert/issues/101) for it over in the webp-convert library

Regarding the redirect, actually I do not want a 301 redirect. The line that produces "x-webp-express: Redirected directly to existing webp" is found in the .htaccess, and is an *internal* redirect. The .htaccess does the redirection internally on the server. In this case, an internal redirect is better than a 301 redirect, because a 301 redirect will cause an extra request. It is faster to return the image directly, with the internal redirect.

**Comment by rosell-dk** [comment]
Fixed, because we are now running webp-convert 2.0
