### ISSUE TITLE
Autocomplete errors

### ISSUE THREAD

**Issue by vijayaraghavanramanan** [rosell-dk/webp-express#371]
If I configure for using a remote web service, the browser tries to autocomplete the fields using the saved user login id and even if ignored, the CDN url is filled with it. 

Saving the setting creates a white screen. 

This happens in Chrome.

**Comment by rosell-dk** [comment]
I do not experience autocomplete errors.
Is it when you click "configure" in the the Remote WebP Express conversion method?
Or is it when you click "+Authorize website"?
Which fields are autocompleted?

Regarding the white screen. Can you try to enable debugging? If you still see white screen, can you try enable debug logging too and check wp-content/debug.log ?
Here is how to enable debugging: https://wordpress.org/support/article/debugging-in-wordpress/

**Comment by rosell-dk** [comment]
I'm btw leaving for today

**Comment by vijayaraghavanramanan** [comment]
The former, when I configure, not when setting up authorizing the website. 

I will try to setup up debugging but pretty sure it's because my user id gets autocompleted in the CDN url. 

So it's probably not a wordpress error, but a browser error. 

This doesn't seem to happen in Edge, only Chrome.

**Comment by rosell-dk** [comment]
The autocomplete doesn't happen for me in Chrome. It could perhaps be a browser extension that does. Or well, Chrome could simply be behaving differently for you. I searched the web and see that [others](https://support.google.com/chrome/thread/8380691?hl=en) are experiencing that Chrome autofills fields it should not. I'm however surprised about this because the URL input doesn't have a name attribute and the "id" attribute is "wpc_api_url" - not something that even remotely resembles "username" in any way. I would have not been as surprised if it was the Api key field because it is a password field.

From [this answer](https://stackoverflow.com/a/55161895/842756) I learned that there exists an attribute called [autocomplete](https://www.w3schools.com/tags/att_input_autocomplete.asp). I will set it to off in the next release.

**Comment by rosell-dk** [comment]
I added autocomplete=off to the input. Please check if it works in the next release (Sorry, I don't know when I shall release yet)

**Comment by vijayaraghavanramanan** [comment]
Sure. I will try to apply the modifications to the plugin files and check myself in advance.

**Comment by rosell-dk** [comment]
Great, thanks :)
