### ISSUE TITLE
"PHP Fatal error" when trying to load settings page

### ISSUE THREAD

**Issue by pfefferle** [rosell-dk/webp-express#393]
When I try to access the settings page, I get a `[27-Jan-2020 07:42:04 UTC] PHP Fatal error:  Access level to WebPConvert\Convert\Converters\BaseTraits\WarningLoggerTrait::logLn() must be public (as in class WebPConvert\Convert\Converters\BaseTraits\OptionsTrait) in /var/www/virtual/ntzblg/html/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/src/Convert/Converters/AbstractConverter.php on line 17`

**Comment by Nintendude89** [comment]
I had the exact same error and managed to fix it by changing some of the functions from "protected" to "public".

If your problem is the same as mine then there are a couple more errors that occur when you fix the first one.

I fixed this by changing "protected" to "public" on the following php files on the following lines:

/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/src/Convert/Converters/BaseTraits/WarningLoggerTrait.php on line 17
/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/src/Convert/Converters/BaseTraits/LoggerTrait.php on line 39
/wp-content/plugins/webp-express/vendor/rosell-dk/webp-convert/src/Convert/Converters/BaseTraits/LoggerTrait.php on line 65

HOWEVER I don't know enough to say whether this is the right way to fix this problem or whether this creates a security hole so if anyone with more knowledge can confirm that would be great.

I'm about to reach out to the developer to see if he can shed some light on this issue, I'll post again on here if I hear anything.

**Comment by rosell-dk** [comment]
The issue is caused by webp-convert and has been solved there (I got a PR): https://github.com/rosell-dk/webp-convert/issues/243#issuecomment-579161495

I have published a new version of both webp-convert and WebP Express with the fix.
