### ISSUE TITLE
Logic in .htaccess for appending Vary header can be simplified

### ISSUE THREAD

**Issue by rosell-dk** [rosell-dk/webp-express#444]
-- and dependency for "mod_setenvif" can be avoided

Solution here:
https://wordpress.org/support/topic/warning-we-did-not-receive-a-varyaccept-header/#post-13323370

**Comment by rosell-dk** [comment]
Hm, actually there is a problem in dispensing with the logic: When Varied Image Responses is used in conjunction with Alter HTML. In that case, the webp's should not have a vary header when requested directly, but only when it a jpg/png has been redirected.

We should therefor only create the simple rules when Alter HTML is disabled.

**Comment by oslobar** [comment]
Hi.

I'm getting this error. What can i do to solve it?

Alrighty. We got the jpeg. Great!.
However, we did not receive a Vary:Accept header. That header should be set in order to tell proxies that the response varies depending on the Accept header. Otherwise browsers not supporting webp might get a cached webp and vice versa.

**Comment by oslobar** [comment]
> Hi.
> 
> I'm getting this error. What can i do to solve it?
> 
> Alrighty. We got the jpeg. Great!. However, we did not receive a Vary:Accept header. That header should be set in order to tell proxies that the response varies depending on the Accept header. Otherwise browsers not supporting webp might get a cached webp and vice versa.

Bump
