### ISSUE TITLE
Path is outside resolved document root

### ISSUE THREAD

**Issue by Akilesso** [rosell-dk/webp-express#526]
When i try to convert images i get error: Path is outside resolved document root.

What could be the problem?
Thanks!

**Comment by davidwebca** [comment]
I also get this nowadays with a roots/bedrock install.

**Comment by LucasDemea** [comment]
Same here with a bedrock install

**Comment by lockemx** [comment]
I may be giving info that is not applicable to most because I am on trellis 1.10.1 + bedrock with WP 6.1, but, if you have symlinks in place, that may be the problem. I have it working on my installs. There's an incompatibility with how realpath is used to check if the image is in the document root. This really may not be your situation because I had the plugin working at first with all live tests passing, but then I tried to use a symlink for the app/webp-express directory.

If you symlink that folder, app/webp-express, (alongside app/uploads) with group write permissions for www-data user to use, the document root will be in a dated folder inside releases directory and the webp-express folder will be in the shared directory, at least as far as realpath reveals to  be the case. I could be wrong, but I think this is the issue.

This code is only necessary to support the releases system for trellis. If you can't get the plugin working, and you didn't try to use symlinks, I am not sure where the issue lies. I am not sure if I configured things in ansible in the most official way either. I ended up just setting up copying of the app/webp-express folder from release to release. I included my config for nginx. The trellis parts should be compatible with Apache.

`roles/deploy/defaults/main.yml` using existing list variables
```
project_copy_folders:
  - vendor
  - "{{ project_public_path }}/app/webp-express"
```

```
project_shared_children:
  - path: "{{ project_public_path }}/{{ project_upload_path }}"
    src: uploads
  - path: "{{ project_public_path }}/app/themes/.htaccess"
    src: themes-htaccess
    type: file
```
`roles/wordpress-setup/templates/wordpress-site.conf.j2` server block
```
  # WebP Express rules
  location ~* ^/?app/.*\.(png|jpe?g)$ {
    add_header Vary Accept;
    expires 365d;
    if ($http_accept !~* "webp"){
      break;
    }
    try_files
      /app/webp-express/webp-images/doc-root/$uri.webp
      $uri.webp
      /app/plugins/webp-express/wod/webp-on-demand.php?xsource=x$request_filename&wp-content=app
      ;
  }

  # Route requests for non-existing webps to the converter
  location ~* ^/?app/.*\.(png|jpe?g)\.webp$ {
      try_files
        $uri
        /app/plugins/webp-express/wod/webp-realizer.php?xdestination=x$request_filename&wp-content=app
        ;
  }
```

**Comment by undisconnected** [comment]
Hey there, I have encountered a problem after migrating my website to a new server. In Webp Express config, I can't choose the value Document root for the destination structure parameter. This causes the images not to display because the path is not the right one. Is there a known reason why this parameter would be disabled and set by default to Image roots?

I'm using nginx both before and after migration. 

Thanks for your help
